name: Content Request
description: Request new files be added to OpenFastDL's file server
title: "[CONTENT]: "
labels: ["content-request"]
body:
  - type: dropdown
    id: game
    attributes:
      label: What game is this content for?
      options:
        - Team Fortress 2
        - "Counter-Strike: Source"
        - "Counter-Strike: Global Offensive"
        - Other
    validations:
      required: true
  - type: checkboxes
    id: verified
    attributes:
      label: Duplicate Verification
      options:
        - label: I have verified that this content has not already been requested, added, or flagged for removal.
          required: true