name: Content Request
description: Request new files be added to OpenFastDL's file servers
title: "[CONTENT]: "
labels: ["content-request"]
body:
  - type: dropdown
    id: game
    attributes:
      label: What game is this content for?
      options:
        - "Team Fortress 2"
        - "Counter-Strike: Source"
        - "Counter-Strike 2"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Content links
      description: Where can this content be safely and reliably be obtained from?
      placeholder: Any necessary links or directions on how or where to download the relevant files should go here.
    validations:
      required: true
  - type: textarea
    id: instructions
    attributes:
      label: Special instructions
      description: Does this content require any special instructions or care with regards to formatting or file structure?
      placeholder: |
        - The file materials/epic/nice.vtf should be renamed to nice2.vtf
        - Files 1.pcf, 2.pcf, and 3.pcf should go in the particles folder
        - Any .bak files can be ignored and do not need to be included
  - type: checkboxes
    id: verified
    attributes:
      label: Duplicate Verification
      options:
        - label: I have verified that this content has not already been requested, added, or flagged for removal.
          required: true
